apiVersion: v1
kind: ConfigMap
metadata:
  name: my-web-html
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif; text-align: center; margin-top: 100px;">
        <h1>Hello from ArgoCD GitOps! 🚀</h1>
        <h2>Version: 1</h2>
      </body>
    </html>
